import React, { useState, useMemo } from 'react';
import { useExpenseStore } from '../../stores/expenseStore';
import { useAuthStore } from '../../stores/authStore';
import { useCategoryStore } from '../../stores/categoryStore';
import { SYSTEM_CATEGORIES } from '../../constants/categories';
import { Check, Calendar, Repeat, Tag, Smile, Frown, Meh, Star, AlertTriangle } from 'lucide-react';
import Button from '../common/Button';
import Input from '../common/Input';
import { addDays, addWeeks, addMonths, addYears } from 'date-fns';
import { processRecurringExpenses } from '../../utils/recurringEngine';

export default function ExpenseForm({ onClose, initialData }) {
  const { addExpense, updateExpense, isSaving } = useExpenseStore();
  const { user } = useAuthStore();
  const { customCategories } = useCategoryStore();

  const formatDateForInput = (dateInput) => {
    try {
      let d;
      if (dateInput?.toDate) d = dateInput.toDate();
      else if (dateInput?.seconds) d = new Date(dateInput.seconds * 1000);
      else if (dateInput) d = new Date(dateInput);
      else d = new Date();

      if (!d || isNaN(d.getTime())) d = new Date();

      const pad = (n) => String(n).padStart(2, '0');
      // ✅ FORMATO MANUAL: Nunca lanza RangeError
      return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
    } catch (e) {
      return new Date().toLocaleDateString('en-CA') + 'T12:00';
    }
  };

  const [form, setForm] = useState({
    amount: initialData?.amount || '',
    description: initialData?.description || '',
    categoryId: initialData?.categoryId || '',
    date: formatDateForInput(initialData?.date),
    isRecurring: initialData?.isRecurring || false,
    frequency: initialData?.frequency || 'daily', // Valor por defecto
    paymentMethod: initialData?.paymentMethod || 'efectivo'
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!user || !form.amount) return;

    const baseDate = new Date(form.date);
    let nextOccurrence = null;

    if (form.isRecurring) {
        // El primer cobro automático es 1 salto después de la fecha elegida
        const start = new Date(baseDate);
        switch (form.frequency) {
            case 'daily': nextOccurrence = addDays(start, 1); break;
            case 'weekly': nextOccurrence = addWeeks(start, 1); break;
            case 'monthly': nextOccurrence = addMonths(start, 1); break;
            case 'yearly': nextOccurrence = addYears(start, 1); break;
            default: nextOccurrence = addDays(start, 1);
        }
    }

    const expenseData = {
      ...form,
      amount: parseFloat(form.amount),
      date: baseDate,
      userId: user.uid,
      isActive: true,
      isAutoGenerated: false,
      nextOccurrence: nextOccurrence
    };

    if (initialData) {
      await updateExpense(initialData.id, expenseData);
    } else {
      await addExpense(expenseData, user.uid);
    }

    if (form.isRecurring) {
        setTimeout(() => processRecurringExpenses(user.uid), 1000);
    }
    onClose();
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="relative">
        <input
          type="number" step="0.01" placeholder="0.00"
          className="w-full py-6 bg-secondary-50 dark:bg-black/20 border-2 border-transparent focus:border-[#FFD700] rounded-[2rem] outline-none text-4xl font-black text-center text-secondary-900 dark:text-white"
          value={form.amount} onChange={e => setForm({...form, amount: e.target.value})}
        />
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-1">
          <label className="text-[10px] font-black uppercase text-secondary-400 ml-2">Fecha</label>
          <input 
            type="datetime-local" 
            className="w-full px-4 py-3 bg-secondary-50 dark:bg-secondary-800 rounded-xl text-xs font-bold outline-none dark:[color-scheme:dark]"
            value={form.date} onChange={e => setForm({...form, date: e.target.value})}
          />
        </div>
        <div className="flex flex-col gap-2">
           <label className="text-[10px] font-black uppercase text-secondary-400 ml-2">¿Recurrente?</label>
           <button 
             type="button" 
             onClick={() => setForm({...form, isRecurring: !form.isRecurring})}
             className={`flex items-center justify-center gap-2 py-3 rounded-xl border-2 transition-all text-xs font-black uppercase ${form.isRecurring ? 'border-purple-500 bg-purple-50 text-purple-600' : 'border-transparent bg-secondary-50 text-secondary-400'}`}
           >
             <Repeat size={16} /> {form.isRecurring ? 'Sí' : 'No'}
           </button>
        </div>
      </div>

      {form.isRecurring && (
        <div className="grid grid-cols-4 gap-2">
          {['daily', 'weekly', 'monthly', 'yearly'].map(freq => (
            <button 
              key={freq} type="button" 
              onClick={() => setForm({...form, frequency: freq})}
              className={`py-2 rounded-lg text-[9px] font-black uppercase border ${form.frequency === freq ? 'bg-purple-500 text-white border-purple-500' : 'bg-transparent border-secondary-200 text-secondary-400'}`}
            >
              {{daily:'Día', weekly:'Sem', monthly:'Mes', yearly:'Año'}[freq]}
            </button>
          ))}
        </div>
      )}

      <Input label="Descripción" value={form.description} onChange={e => setForm({...form, description: e.target.value})} />

      <div className="flex gap-3 pt-4">
        <Button variant="secondary" onClick={onClose} className="flex-1">CANCELAR</Button>
        <Button variant="primary" className="flex-[2]" onClick={handleSubmit} loading={isSaving}>
          <Check className="mr-2" size={18} /> {initialData ? 'ACTUALIZAR' : 'GUARDAR'}
        </Button>
      </div>
    </form>
  );
}