import React, { useEffect, useMemo, useState } from 'react';
import { useExpenseStore } from '../stores/expenseStore';
import { useAuthStore } from '../stores/authStore';
import { useCategoryStore } from '../stores/categoryStore'; 
import { useUIStore } from '../stores/uiStore';
import { ArrowLeft, Power, Loader2, Trash2, RefreshCw, Calendar, Repeat, Tag, Hash, Flag, Infinity, Clock, CreditCard } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import * as LucideIcons from 'lucide-react';
import { SYSTEM_CATEGORIES } from '../constants/categories';
import { processRecurringExpenses } from '../utils/recurringEngine';
import { differenceInDays, startOfDay, addDays } from 'date-fns';
import QuickAddModal from '../components/expenses/QuickAddModal';

const ICON_LOOKUP = { ...LucideIcons };

// --- COMPONENTE: Barra de Progreso ---
const ProgressBar = ({ current, total, color }) => {
  const percentage = Math.min(100, Math.max(0, (current / total) * 100));
  
  return (
    <div className="h-3 w-full bg-black/10 dark:bg-white/10 rounded-full overflow-hidden">
      <div 
        className="h-full rounded-full transition-all duration-1000 relative"
        style={{ width: `${percentage}%`, backgroundColor: color }}
      >
        <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/30 to-transparent animate-shimmer" />
      </div>
    </div>
  );
};

const RecurringExpenses = () => {
  const { expenses, subscribeExpenses, updateExpense, deleteExpense, loading } = useExpenseStore();
  const { user } = useAuthStore();
  const { customCategories, subscribeCategories } = useCategoryStore();
  const { openQuickAddModal } = useUIStore();
  const navigate = useNavigate();
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    if (user) {
      subscribeExpenses(user.uid);
      subscribeCategories(user.uid);
    }
  }, [user, subscribeExpenses, subscribeCategories]);

  const allCategories = useMemo(() => [...SYSTEM_CATEGORIES, ...(customCategories || [])], [customCategories]);

  const recurringTemplates = useMemo(() => {
    if (!expenses) return [];
    
    const masters = expenses.filter(e => e.isRecurring === true && e.isAutoGenerated !== true);
    
    return masters.map(master => {
        const children = expenses.filter(e => e.masterRecurringId === master.id);
        const totalPaid = children.reduce((sum, child) => sum + Number(child.amount), 0) + Number(master.amount);
        // El conteo incluye al padre + los hijos
        const count = children.length + 1; 

        const cat = allCategories.find(c => c.id === master.categoryId);
        let subLabel = master.subcategoryName;
        if (!subLabel && master.subcategoryId && cat?.subcategories) {
            const sub = cat.subcategories.find(s => s.id === master.subcategoryId);
            if (sub) subLabel = sub.label;
        }
        
        // ✅ CÁLCULO PRECISO DE PAGOS TOTALES
        let totalExpectedPayments = null;
        let isFinite = false;

        if (master.endDate) {
          isFinite = true;
          // Usamos la fecha de creación (date) como inicio seguro
          let startDateRef = master.date ? (master.date.seconds ? new Date(master.date.seconds * 1000) : new Date(master.date)) : new Date();
          
          let endDateRef = master.endDate.seconds ? new Date(master.endDate.seconds * 1000) : new Date(master.endDate);
          
          // Normalizamos a medianoche para contar días completos
          const start = startOfDay(startDateRef);
          const end = startOfDay(endDateRef);
          
          // Diferencia en días + 1 (para incluir el día de inicio)
          const daysDiff = differenceInDays(end, start) + 1;
          
          if (master.frequency === 'daily') totalExpectedPayments = daysDiff;
          else if (master.frequency === 'weekly') totalExpectedPayments = Math.ceil(daysDiff / 7);
          else if (master.frequency === 'biweekly') totalExpectedPayments = Math.ceil(daysDiff / 14);
          else if (master.frequency === 'monthly') totalExpectedPayments = Math.ceil(daysDiff / 30);
          else if (master.frequency === 'yearly') totalExpectedPayments = Math.ceil(daysDiff / 365);
          
          // Seguridad: Si por error da menos que lo actual, forzamos al actual
          if (totalExpectedPayments < count) totalExpectedPayments = count;
        }
        
        return {
            ...master,
            color: master.categoryColor || cat?.color || '#FFD700',
            categoryName: cat?.label || master.categoryName,
            subLabel: subLabel,
            stats: {
                totalSpent: totalPaid,
                occurrencesCount: count,
                totalExpectedPayments: totalExpectedPayments,
                isFinite: isFinite
            }
        };
    });
  }, [expenses, allCategories]);

  const handleToggle = async (expense) => {
    await updateExpense(expense.id, { isActive: !expense.isActive });
  };

  const handleDelete = async (id) => {
    if(window.confirm('¿Eliminar gasto recurrente permanentemente?')) {
      await deleteExpense(id);
    }
  };

  const handleSync = async () => {
    if (!user) return;
    setIsProcessing(true);
    try {
        await processRecurringExpenses(user.uid);
    } catch (e) { console.error(e); } 
    finally { setIsProcessing(false); }
  };

  const getNextDateLabel = (dateVal) => {
    if (!dateVal) return 'Finalizado';
    try {
      const d = dateVal.seconds ? new Date(dateVal.seconds * 1000) : new Date(dateVal);
      return d.toLocaleDateString('es-MX', { day: 'numeric', month: 'long' });
    } catch (e) { return 'Error'; }
  };

  const getCategoryIcon = (catId) => {
    const cat = allCategories.find(c => c.id === catId);
    if (!cat) return CreditCard;
    if (typeof cat.icon === 'function' || typeof cat.icon === 'object') return cat.icon;
    const iconName = cat.iconName || (typeof cat.icon === 'string' ? cat.icon : null);
    if (iconName && ICON_LOOKUP[iconName]) return ICON_LOOKUP[iconName];
    return CreditCard;
  };

  const getFrequencyLabel = (freq) => {
    const map = { daily: 'Diario', weekly: 'Semanal', biweekly: 'Quincenal', monthly: 'Mensual', yearly: 'Anual' };
    return map[freq] || freq;
  };

  const totalMonthlyCommitment = recurringTemplates.reduce((acc, item) => {
      if (item.isActive) return acc + Number(item.amount);
      return acc;
  }, 0);

  return (
    <div className="pb-32 pt-6 px-4 max-w-6xl mx-auto min-h-screen animate-in fade-in duration-500">
      
      {/* HEADER TIPO DASHBOARD */}
      <div className="relative mb-8 p-8 rounded-[2.5rem] bg-[#FFD700] text-[#1e1b4b] shadow-2xl overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-white/20 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2"></div>
        
        <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
            <div>
                <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-[#1e1b4b]/60 hover:text-[#1e1b4b] mb-4 transition-colors">
                    <ArrowLeft size={20} /> <span className="text-xs font-black uppercase tracking-widest">Volver</span>
                </button>
                <h1 className="text-4xl md:text-5xl font-black uppercase tracking-tighter leading-none mb-2">
                    Recurrentes
                </h1>
                <p className="text-sm font-bold opacity-80">
                    Tu compromiso mensual es de <span className="font-black text-xl">${totalMonthlyCommitment.toLocaleString()}</span>
                </p>
            </div>

            <button 
                onClick={handleSync} 
                disabled={isProcessing}
                className="bg-[#1e1b4b] text-[#FFD700] px-6 py-4 rounded-2xl font-black text-xs uppercase tracking-widest shadow-xl hover:scale-105 active:scale-95 transition-all flex items-center gap-3"
            >
                <RefreshCw size={18} className={isProcessing ? "animate-spin" : ""} />
                {isProcessing ? 'Sincronizando...' : 'Sincronizar Ahora'}
            </button>
        </div>
      </div>

      {loading ? (
        <div className="flex justify-center py-20"><Loader2 className="animate-spin text-[#FFD700]" size={40} /></div>
      ) : (
        <div className="space-y-4">
          {recurringTemplates.map(item => {
            const Icon = getCategoryIcon(item.categoryId);
            const isPaused = !item.isActive;
            const itemColor = item.color;
            const remainingPayments = item.stats.isFinite ? item.stats.totalExpectedPayments - item.stats.occurrencesCount : null;

            return (
              <div 
                key={item.id} 
                className={`group relative overflow-hidden p-6 rounded-[2.5rem] transition-all duration-300 ${
                  isPaused 
                    ? 'bg-secondary-100 dark:bg-secondary-900 border-2 border-dashed border-secondary-300 dark:border-secondary-700 opacity-70' 
                    : 'bg-white dark:bg-secondary-900 border border-secondary-100 dark:border-secondary-800 shadow-lg hover:shadow-xl hover:scale-[1.01]'
                }`}
              >
                {/* Indicador lateral de color */}
                <div className="absolute left-0 top-0 bottom-0 w-2" style={{ backgroundColor: isPaused ? '#9ca3af' : itemColor }} />

                <div className="flex flex-col md:flex-row gap-6 items-start md:items-center pl-4">
                    
                    {/* ICONO Y TEXTO */}
                    <div className="flex items-center gap-5 flex-1">
                        <div 
                            className={`w-16 h-16 rounded-2xl flex items-center justify-center text-3xl shadow-lg ${isPaused ? 'bg-secondary-200 text-secondary-400' : 'text-white'}`}
                            style={{ backgroundColor: isPaused ? undefined : itemColor }}
                        >
                            <Icon size={32} />
                        </div>
                        <div>
                            <h3 className="text-xl font-black text-secondary-900 dark:text-white leading-none mb-1">
                                {item.description || item.categoryName}
                            </h3>
                            <div className="flex items-center gap-2 text-secondary-500 dark:text-secondary-400 text-xs font-bold">
                                <span>{item.categoryName}</span>
                                {item.subLabel && <span className="opacity-50">/ {item.subLabel}</span>}
                            </div>
                            <div className="flex items-center gap-2 mt-2">
                                <span className="px-2 py-0.5 bg-secondary-100 dark:bg-white/5 rounded-md text-[10px] font-black uppercase tracking-wider text-secondary-500">
                                    {getFrequencyLabel(item.frequency)}
                                </span>
                                {item.stats.isFinite && (
                                    <span className="flex items-center gap-1 text-[10px] font-bold text-amber-500">
                                        <Flag size={10} /> Meta Fija
                                    </span>
                                )}
                            </div>
                        </div>
                    </div>

                    {/* ESTADÍSTICAS Y BARRA */}
                    <div className="flex-1 w-full md:w-auto">
                        <div className="flex justify-between items-end mb-2">
                            <span className="text-[10px] font-black uppercase text-secondary-400 tracking-widest">
                                {item.stats.isFinite ? `Progreso (${item.stats.occurrencesCount}/${item.stats.totalExpectedPayments})` : 'Histórico de Pagos'}
                            </span>
                            <span className="text-xs font-bold text-secondary-900 dark:text-white">
                                Total: ${item.stats.totalSpent.toLocaleString()}
                            </span>
                        </div>
                        
                        {item.stats.isFinite ? (
                            <ProgressBar 
                                current={item.stats.occurrencesCount} 
                                total={item.stats.totalExpectedPayments} 
                                color={itemColor} 
                            />
                        ) : (
                            // Barra infinita para suscripciones
                            <div className="h-3 w-full bg-secondary-100 dark:bg-white/5 rounded-full overflow-hidden relative">
                                <div className="absolute inset-0 bg-gradient-to-r from-transparent via-secondary-300/20 to-transparent animate-shimmer" />
                                <div className="h-full w-1/3 rounded-full opacity-30" style={{ backgroundColor: itemColor }}></div>
                            </div>
                        )}

                        <div className="mt-2 flex justify-between items-center text-[10px] font-bold text-secondary-500">
                            <span className="flex items-center gap-1">
                                {item.stats.isFinite 
                                    ? (remainingPayments > 0 ? `${remainingPayments} pagos restantes` : '¡Completado!')
                                    : <><Infinity size={12} /> Suscripción activa</>
                                }
                            </span>
                            <span className="flex items-center gap-1 text-emerald-600 dark:text-emerald-400">
                                <Clock size={12} /> Próximo: {getNextDateLabel(item.nextOccurrence)}
                            </span>
                        </div>
                    </div>

                    {/* PRECIO Y ACCIONES */}
                    <div className="flex flex-row md:flex-col items-center md:items-end gap-4 w-full md:w-auto justify-between md:justify-center border-t md:border-t-0 border-secondary-100 dark:border-white/5 pt-4 md:pt-0">
                        <div className="text-right">
                            <span className="block text-[10px] font-black uppercase text-secondary-400 tracking-widest">Monto Fijo</span>
                            <span className="block text-3xl font-black text-secondary-900 dark:text-white tracking-tighter">
                                ${Number(item.amount).toLocaleString()}
                            </span>
                        </div>
                        
                        <div className="flex gap-2">
                            <button onClick={() => handleToggle(item)} className={`p-2 rounded-xl transition-colors ${!isPaused ? 'bg-emerald-100 text-emerald-600' : 'bg-secondary-200 text-secondary-500'}`}>
                                <Power size={18} />
                            </button>
                            <button onClick={() => handleDelete(item.id)} className="p-2 bg-red-50 text-red-500 hover:bg-red-100 rounded-xl transition-colors">
                                <Trash2 size={18} />
                            </button>
                        </div>
                    </div>

                </div>
              </div>
            );
          })}
        </div>
      )}
      
      <QuickAddModal />

      {recurringTemplates.length === 0 && !loading && (
        <div className="flex flex-col items-center justify-center py-20 opacity-40">
          <Repeat size={48} className="text-secondary-300 mb-4" />
          <p className="text-sm font-black uppercase text-secondary-400">No hay gastos recurrentes</p>
        </div>
      )}
    </div>
  );
};

// Agregar animación shimmer
const style = document.createElement('style');
style.textContent = `
  @keyframes shimmer {
    0% { transform: translateX(-100%); }
    100% { transform: translateX(200%); }
  }
  .animate-shimmer {
    animation: shimmer 2s infinite;
  }
`;
document.head.appendChild(style);

export default RecurringExpenses;