import { addDoc, collection, serverTimestamp, doc, updateDoc } from 'firebase/firestore';
import { db } from '../firebase/config';
import { addDays, addWeeks, addMonths, isBefore, isSameDay } from 'date-fns';

export const processRecurringExpenses = async (expenses, updateExpenseInStore) => {
  const today = new Date();
  // Filtramos configuraciones de gastos recurrentes (no los autogenerados)
  const recurrentConfigs = expenses.filter(e => e.isRecurring && e.nextOccurrence && !e.isAutoGenerated);

  for (const config of recurrentConfigs) {
    const nextDate = config.nextOccurrence.toDate ? config.nextOccurrence.toDate() : new Date(config.nextOccurrence);
    
    if (isBefore(nextDate, today) || isSameDay(nextDate, today)) {
      try {
        // 1. Crear el gasto del periodo actual
        const newExpense = {
          amount: config.amount,
          categoryId: config.categoryId,
          categoryName: config.categoryName,
          description: `${config.description} (Auto)`,
          userId: config.userId,
          date: nextDate, // La fecha que correspondía al cargo
          createdAt: serverTimestamp(),
          isAutoGenerated: true,
          type: 'expense',
          isImpulse: false
        };

        await addDoc(collection(db, 'expenses'), newExpense);

        // 2. Calcular la siguiente fecha de ocurrencia
        let updatedNextDate = new Date(nextDate);
        if (config.frequency === 'daily') updatedNextDate = addDays(updatedNextDate, 1);
        if (config.frequency === 'weekly') updatedNextDate = addWeeks(updatedNextDate, 1);
        if (config.frequency === 'monthly') updatedNextDate = addMonths(updatedNextDate, 1);

        // 3. Actualizar el documento de configuración original
        await updateDoc(doc(db, 'expenses', config.id), {
          nextOccurrence: updatedNextDate,
          lastProcessed: serverTimestamp()
        });

      } catch (error) {
        console.error("Error en motor de recurrencia:", error);
      }
    }
  }
};