import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase/config';

export const processRecurringExpenses = async (expenses, userId) => {
  const today = new Date();
  const recurrents = expenses.filter(e => e.isRecurring && e.nextOccurrence);

  for (const exp of recurrents) {
    const nextDate = new Date(exp.nextOccurrence);
    
    if (today >= nextDate) {
      // 1. Clonar el gasto
      const newExpense = {
        ...exp,
        date: new Date(),
        createdAt: serverTimestamp(),
        isAutoGenerated: true
      };
      delete newExpense.id;

      // 2. Calcular próxima fecha según frecuencia
      let updatedNextDate = new Date(nextDate);
      if (exp.frequency === 'daily') updatedNextDate.setDate(updatedNextDate.getDate() + 1);
      if (exp.frequency === 'weekly') updatedNextDate.setDate(updatedNextDate.getDate() + 7);
      if (exp.frequency === 'monthly') updatedNextDate.setMonth(updatedNextDate.getMonth() + 1);

      try {
        await addDoc(collection(db, 'expenses'), newExpense);
        // Aquí se debería actualizar el documento original con la nueva nextOccurrence
        // (Requiere updateExpense en el store)
      } catch (error) {
        console.error("Error en automatización:", error);
      }
    }
  }
};